name: dependency-review

on:
  - pull_request

permissions: {}

jobs:
  dependency-review:
    permissions:
      contents: read
    uses: escapace/workflows/.github/workflows/dependency-review.yaml@trunk
